- name: Ensure hosts is up and running
  hosts: bitops_servers
  gather_facts: no
  tasks:
  - name: Wait for hosts to come up
    wait_for_connection:
      timeout: 300

- name: Ansible tasks
  hosts: bitops_servers
  become: true
  tasks:
  - name: Include install
    include_tasks: tasks/install.yml
  - name: Include fetch
    include_tasks: tasks/fetch.yml

    # Notes on why unmounting is required can be found in umount.yaml
  - name: Unmount efs
    include_tasks: tasks/umount.yml
  - name: Mount efs
    include_tasks: tasks/mount.yml
    when: mount_efs
  - name: Include start
    include_tasks: tasks/start.yml